.\" Manpage for ruby_sources.
.\" Contact bauwen_j@epitech.eu .in to correct errors or typos.
.TH man 1 " 2013" "1.0" "108monstre man page"

.SH NAME
108monstre

.SH SYNOPSIS

.P
\fB./108monstre\fR <\fIcoef a\fR> <\fInmax\fR>
.P
.SH DESCRIPTION

List of the mods :

.SH SEE ALSO
No related manpage.

.SH REPORTING BUGS
No known bugs.

.br
Report ./108monster bugs to jordan.bauwens@epitech.eu
.SH AUTHOR
bauwen_j


